window.DEFAULT_APP_CONFIG = {
  version: '1.1.0',
  form: {
    title: '入职资料自助收集',
    subtitle: '请按照下方流程准备并填写，预计耗时 5-10 分钟。',
    zipPasswordHint: '请输入人事约定的 ZIP 解压密码。页面不会保存该密码。'
  },
  limits: {
    defaultMaxSizeMB: 20,
    defaultMaxFiles: 10,
    maxTotalSizeMB: 200
  },
  naming: {
    zipNameTemplate: '{姓名}_{手机号}_入职资料包_{日期}.zip',
    fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}'
  },
  email: {
    to: '',
    cc: '',
    subjectTemplate: '【入职资料】{姓名}-{手机号}',
    bodyTemplate: '您好：\n\n我的入职资料已整理为加密压缩包，请查收附件。\n\n姓名：{姓名}\n手机号：{手机号}\n资料包名称：{压缩包名称}\n\n压缩包已加密，解压密码请使用约定密码。\n\n谢谢。'
  },
  baseFields: [
    {
      sort: 1,
      key: '姓名',
      label: '姓名',
      type: 'text',
      required: true,
      placeholder: '请输入姓名'
    },
    {
      sort: 2,
      key: '手机号',
      label: '手机号',
      type: 'phone',
      required: true,
      placeholder: '请输入手机号'
    }
  ],
  attachments: [
    {
      sort: 1,
      id: 'attachment_04_id_card',
      code: '附件01',
      name: '身份证',
      required: true,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
      maxFiles: 4,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '1. 请提交身份证正反面合并在同一页的图片；\n2. 报到现场需携带身份证原件。'
    },
    {
      sort: 2,
      id: 'attachment_05_political_review',
      code: '附件02',
      name: '政审报告',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 5,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '1. 需通过人事部模板填写并盖章；\n2. 如果保管机构没有模板，可联系入事接口提供公司模板。'
    },
    {
      sort: 3,
      id: 'attachment_06_education_certificate',
      code: '附件03',
      name: '学历证书',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 6,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '提供完整学历证书，如硕士研究生，应提供硕士、本科毕业证书；报到当天验原件。'
    },
    {
      sort: 4,
      id: 'attachment_07_education_verification',
      code: '附件04',
      name: '学历学信网验证报告',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 6,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '请提供与学历证书对应的学信网验证报告，确保姓名、证书信息清晰完整。'
    },
    {
      sort: 5,
      id: 'attachment_08_degree_certificate',
      code: '附件05',
      name: '学位证书',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 6,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '提供完整学位证书，如硕士，应提供学士、硕士学位证书；报到当天验原件。'
    },
    {
      sort: 6,
      id: 'attachment_09_degree_verification',
      code: '附件06',
      name: '学位学信网验证报告',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 6,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '请提供与学位证书对应的学信网验证报告，确保姓名、学位信息清晰完整。'
    },
    {
      sort: 7,
      id: 'attachment_08_medical_report',
      code: '附件07',
      name: '体检报告电子件',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 5,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '若原件为电子件，直接上传原件；若为纸质件，需扫描提供 PDF，纸质原件报到当天提交。'
    },
    {
      sort: 8,
      id: 'attachment_09_no_criminal_record',
      code: '附件08',
      name: '无犯罪记录证明',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 5,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '若原件为电子件，直接上传原件；若为纸质件，需扫描提供 PDF，纸质原件报到当天提交。'
    },
    {
      sort: 9,
      id: 'attachment_10_resignation_certificate',
      code: '附件09',
      name: '上一家单位离职证明',
      required: true,
      isTemplate: false,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 5,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '若原件为电子件，直接上传原件；若为纸质件，需扫描提供 PDF，报到当天提交原件。'
    },
    {
      sort: 10,
      id: 'attachment_11_resume_template',
      code: '附件10',
      name: '中粮贸易新员工信息登记表',
      required: true,
      isTemplate: true,
      allowedExtensions: ['doc', 'docx', 'pdf'],
      maxFiles: 2,
      maxSizeMB: 20,
      templateUrl: '中粮贸易新员工信息登记表.docx',
      exampleImageUrl: '中粮贸易新员工信息登记表示例.png',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '请点击下载模板，按要求填写后上传。'
    },
    {
      sort: 11,
      id: 'attachment_12_relative_employment',
      code: '附件11',
      name: '招聘人员近亲属系统内从业情况',
      required: true,
      isTemplate: true,
      allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
      maxFiles: 3,
      maxSizeMB: 20,
      templateUrl: '招聘人员近亲属系统内从业情况.docx',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '请下载模板打印，手写填写并签字后，扫描或拍照上传。'
    },
    {
      sort: 12,
      id: 'attachment_12_employee_info',
      code: '附件12',
      name: '粮达网新员工信息登记表',
      required: true,
      isTemplate: true,
      allowedExtensions: ['doc', 'docx', 'xls', 'xlsx', 'pdf'],
      maxFiles: 2,
      maxSizeMB: 20,
      templateUrl: '粮达网新员工信息登记表.docx',
      exampleImageUrl: '粮达网新员工信息登记表示例.png',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '请点击下载模板，按要求填写后上传。'
    },
    {
      sort: 13,
      id: 'attachment_13_social_security_card',
      code: '附件13',
      name: '社保卡',
      required: true,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
      maxFiles: 3,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '拍摄社保卡正面；如深圳没有参保经历请提供社保缴纳截图。'
    },
    {
      sort: 14,
      id: 'attachment_14_agricultural_bank_card',
      code: '附件14',
      name: '中国农业银行卡',
      required: true,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
      maxFiles: 3,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '拍摄包含卡号的一面即可，用于核对卡号。'
    },
    {
      sort: 15,
      id: 'attachment_15_housing_fund_card',
      code: '附件15',
      name: '公积金卡',
      required: true,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
      maxFiles: 3,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '保存微信、支付宝等途径的显示公积金卡号的截图；如有正式实体卡，拍照上传。'
    },
    {
      sort: 16,
      id: 'attachment_16_photos',
      code: '附件16',
      name: '寸白底证件照和生活照',
      required: true,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png'],
      maxFiles: 10,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '电子件或照片直接上传，报到当天提供相片。'
    },
    {
      sort: 17,
      id: 'attachment_99_other',
      code: '附件17',
      name: '其他材料',
      required: false,
      isTemplate: false,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx', 'xls', 'xlsx'],
      maxFiles: 20,
      maxSizeMB: 20,
      templateUrl: '',
      exampleImageUrl: '',
      fileNameTemplate: '{姓名}_{手机号}_{附件编号}_{资料名称}_{序号}.{扩展名}',
      description: '若人事沟通时要求提供荣誉证书等，请在此上传。'
    }
  ]
};
